title: Amanda Pinsker
description: Portfolio website for Amanda Pinsker
baseurl: ""
url: "https://Etterlivet.github.io" # Replace with your GitHub Pages URL

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  projects:
    output: false

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
